﻿

#  ВВЕДЕНИЕ

В современной промышленности автоматизация производственных процессов играет ключевую роль в обеспечении эффективности, гибкости и качества производства. Стремительное развитие технологий и растущие требования рынка предъявляют высокие стандарты к производственным системам, которые могут быть достигнуты только с помощью эффективной автоматизации.

Одним из фундаментальных аспектов автоматизации производства является обеспечение связи и передачи данных в промышленной среде. Для этого широко применяются производственные сетевые протоколы, которые предоставляют надежные и эффективные средства коммуникации между устройствами и системами в производственной среде.

Целью данного дипломного проекта является реализация модуля работы с протоколом PROFINET на базе микроконтроллера AXC F 2152 от компании Phoenix Contact в рамках управляющей программы ptusa\_main. Этот модуль предоставит функциональность для взаимодействия с сетевым протоколом PROFINET, обеспечивая установление связи с другими устройствами в промышленной сети, передачу и прием данных, а также логику управления.

Проект ptusa\_main, на основе которого разрабатывается данный модуль, представляет собой открытый исходный код программного обеспечения, размещенный на платформе GitHub (ссылка: https://github.com/savushkin-r-d/ptusa\_main). Он представляет собой комплексную систему управления производственными процессами, включающую различные функциональные модули, включая модуль работы с протоколом PROFINET. Разработка управляющего модуля на базе микроконтроллера AXC F 2152 значительно расширит функциональные возможности проекта ptusa\_main и обеспечит более надежную связь и передачу данных в производственной среде.

В разработке модуля работы с протоколом PROFINET необходимо учесть особенности и требования этого протокола, а также возможности, предоставляемые микроконтроллером AXC F 2152. Также требуется провести настройку сетевой конфигурации, определить параметры и обработку ошибок. В результате успешной реализации модуля работы с протоколом PROFINET на базе микроконтроллера AXC F 2152, управляющая программа ptusa\_main получит возможность взаимодействия с другими устройствами в промышленной сети, обеспечивая эффективную коммуникацию и передачу данных в реальном времени. Это позволит оптимизировать производственные процессы, обеспечивать точность и надежность передачи информации, а также управлять системой автоматизации производства с высокой гибкостью и расширяемостью.

Таким образом, данный дипломный проект имеет важное практическое значение, предоставляя решение для эффективной автоматизации производственных процессов с использованием современных сетевых протоколов, анализ автоматизации производственных процессов и производственных сетевых протоколов, роли производственных сетевых протоколов в обеспечении связи и передачи данных в промышленных сетях, рассмотрены особенности и преимущества PROFINET, а также проведен сравнительный анализ с другими протоколами. Разработка модуля работы с протоколом PROFINET на базе микроконтроллера AXC F 2152 в рамках проекта ptusa\_main позволит расширить его функциональность и повысить его конкурентоспособность в сфере промышленной автоматизации.


#  1  АНАЛИЗ ПРЕДМЕТНОЙ ОБЛАСТИ И ПОСТАНОВКА ЗАДАЧИ

   ## 1.1 Методы и спёособы автоматизации производства

**Автоматизация производства** - это применение автоматизированных систем и технологий для управления и контроля различных производственных операций, таких как сборка, обработка, инспекция, транспортировка и хранение продукции. Автоматизация производства позволяет сократить затраты на труд, материалы и энергию, повысить качество и безопасность продукции, ускорить процессы и улучшить условия труда. Автоматизация производства включает в себя ряд методов и технологий, которые могут применяться в различных отраслях промышленности и секторах. Вот некоторые из них:

- **Системы машинного зрения:** технология машинного зрения позволяет обрабатывать и анализировать визуальные данные с помощью компьютерных систем. Она может использоваться для автоматического контроля качества, распознавания объектов, ориентации и навигации роботов, определения положения и т.д.
- **Системная интеграция:**  автоматизация производства также подразумевает интеграцию различных систем и компонентов для создания единой среды автоматизации. Например, система управления производством (MES) может быть интегрирована с системой планирования ресурсов предприятия (ERP) для обмена информацией о заказах, материалах и производственных операциях. Это позволяет автоматически синхронизировать данные и оптимизировать производственные процессы.
- **Программируемые логические контроллеры (ПЛК):** ПЛК - это специализированные устройства, используемые для мониторинга и управления процессами в производстве. Они могут быть запрограммированы на автоматическое выполнение различных операций, контроль параметров и реагирование на изменения в системе..
- **Системы автоматической идентификации:** штрих-коды, RFID (радиочастотные идентификационные метки) и другие системы для маркировки и идентификации продукции. Они могут автоматически распознавать и отслеживать товары и компоненты в процессе производства.
- **Автоматизированные системы хранения и логистики:** Эффективное управление хранением и распределением материалов и готовой продукции имеет важное значение в производственном процессе. Автоматизированные складские системы, такие как автоматизированные конвейеры, роботизированные системы перемещения и системы управления складом, оптимизируют процессы приема, хранения и отгрузки товаров.
- **Цифровой двойник:** Цифровой двойник - это виртуальная модель реального объекта, системы или процесса. Он позволяет моделировать, анализировать и оптимизировать параметры производственных операций без вмешательства в физическую среду.
- **Робототехника:** роботы используются для автоматизации различных задач на производственных линиях. Они могут выполнять задачи с высокой степенью точности и повторяемости и способны работать в опасных или труднодоступных средах. Промышленные роботы могут выполнять такие задачи, как сборка, сварка, покраска, погрузка и разгрузка, а также упаковка.
- **Аналитика данных и искусственный интеллект:** Обработка больших данных и использование алгоритмов искусственного интеллекта позволяют автоматизировать анализ, прогнозирование и принятие решений. Это включает мониторинг производственных данных, выявление аномалий и проблем, оптимизацию производственных параметров, прогнозирование отказов оборудования и оптимизацию планирования производственных операций. 
- ` `**Автоматизация управления закупками и запасами:** автоматизация также может применяться к управлению закупками и запасами. Сюда входит автоматическое управление и контроль уровня запасов, автоматическая передача заказов поставщикам, контроль сроков годности и отслеживание поставок. Автоматизация процесса закупок позволяет сократить время доставки, минимизировать ошибки и оптимизировать уровень запасов в соответствии с потребностями производства. 
- ` `**Виртуальная и дополненная реальность:** виртуальная и дополненная реальность может использоваться в производстве для визуализации процессов, обучения персонала, моделирования и имитации работы; технологии VR и AR могут использоваться для создания виртуальных моделей оборудования, обучения операторов, визуализации производственных данных, проектирования новых систем и процессов. 
- ` `**Автоматизированный транспорт и логистика:** Автоматизация на производстве может применяться для автоматизированного перемещения и обработки материалов и готовой продукции. Сюда входят автоматизированные транспортные системы, конвейеры, автономные транспортные средства и системы управления логистикой. Автоматизация транспорта и логистики может помочь повысить эффективность, сократить время доставки и оптимизировать планирование поставок. 
- ` `**Автоматизация обслуживания и ремонта:** автоматизация может применяться не только к производственным процессам, но и к обслуживанию и технической поддержке. Сюда входит автоматический мониторинг оборудования, диагностика и прогнозирование неисправностей, автоматическая диагностика и удаленное управление оборудованием. Автоматизированные системы технического обслуживания способствуют повышению эксплуатационной готовности, сокращению времени простоя и оптимизации процессов технической поддержки. 

  ##  1.2 Основные теоретические сведения и понятия

**Объект автоматизации** - это технологический процесс, устройство, агрегат, линия или цех, в которых функции управления и контроля, ранее выполнявшиеся человеком, передаются приборам и автоматическим устройствам. Объекты автоматизации на производстве могут быть различными по степени сложности, масштабу, функциональности и типу обмена данными. Объекты автоматизации на производстве могут быть частично, комплексно или полностью автоматизированы в зависимости от целей и задач производства 

**Цех -** это структурная единица предприятия, в которой осуществляется производство определенного вида продукции или услуг. Цеха часто автоматизируются с целью улучшения эффективности, точности и скорости производства. Цеха могут специализироваться на определенном виде производства, например, металлообработке, производстве пластмасс или электроники. Они также могут отличаться по своей организации, размеру и степени автоматизации. 

**Протоколы -** в сетевых коммуникациях протоколы - это набор правил и стандартов, определяющих порядок организации, отправки и получения данных между устройствами в компьютерной сети. Промышленный протокол - это протокол передачи данных, который адаптирован к специфике и требованиям промышленной среды, таким как высокая надежность, скорость, детерминизм и защита от помех.

**Ethernet -** один из наиболее распространенных протоколов, используемых в локальных вычислительных сетях (ЛВС). Он определяет методы доступа к сети, форматы кадров данных, скорость передачи и другие параметры. Ethernet позволяет компьютерам, серверам, устройствам хранения данных и другим сетевым устройствам подключаться к одной сети и обмениваться информацией.

**Программно-аппаратные платформы** - это совокупность аппаратных и программных средств, которые образуют базовый уровень для разработки и запуска прикладных программ. Программно-аппаратные платформы определяют архитектуру, интерфейсы и стандарты, которые должны соблюдаться при создании и использовании программного обеспечения.

**Контроллер** - это электронное устройство или компьютерная система, которая служит для управления и контроля технологическими процессами, системами и оборудованием в промышленной среде. Контроллер обеспечивает точность и надежность в управлении, автоматически регулирует параметры процесса, обеспечивает безопасность и повышает эффективность производства. Контроллеры могут быть различными по своему типу и функциональности, в зависимости от специфики задач автоматизации и управления.

## 1.3 Анализ и описание сетевых протоколов в контексте автоматизации производства**

Промышленные сетевые протоколы относятся к специальному классу промышленных протоколов, которые разработаны для обмена данными в промышленных сетях. Они регламентируют правила передачи данных между различными устройствами и системами внутри сети и обеспечивают их совместимость и взаимодействие. Промышленные сетевые протоколы учитывают требования промышленной среды и обладают такими характеристиками, как высокая надежность передачи данных, минимальная задержка, устойчивость к помехам и широкий радиус действия. Они основаны на многоуровневом принципе, при котором каждый уровень выполняет определенные функции и обменивается данными с соседними уровнями. Существует множество сетевых протоколов для разных целей и задач. Например, протоколы IP и TCP являются основой работы интернета, а протоколы Ethernet и WiFi используются для локальных сетей. 

Производственные протоколы также имеют различные уровни абстракции и функциональности в зависимости от слоя коммуникации. Обычно выделяют три слоя коммуникации в производственных сетях:

- Слой полевых устройств - этот слой состоит из большого количества датчиков, преобразователей и исполнительных устройств. Они обеспечивают сбор и передачу данных о состоянии и параметрах процесса.
- Слой управления - этот слой включает в себя логические контроллеры, которые могут быть распределенными или централизованными. Они агрегируют данные с полевых устройств и передают их в более крупные системы управления предприятием.
- Слой надзора - этот слой содержит системы управления предприятием с человеко-машинными интерфейсами для управления процессами. Они также могут обеспечивать связь с внешними системами, такими как интернет или облачные сервисы.

![https://helpiks.org/helpiksorg/baza2/274777875999.files/image003.jpg](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.003.jpeg)

Рисунок 1.1 – Обобщенная архитектура АСУ

Классификация сетевых протоколов часто основывается на различных аспектах их функций. Распространенным подходом к классификации является модель Open Systems Interconnection (OSI), которая определяет семь уровней или слоев в компьютерных сетях, где происходит обработка и передача данных. Каждый уровень выполняет определенную функцию и взаимодействует с соседними уровнями.

На следующуй страницу приведена классификация протоколов, основанная на модели OSI:

- Физический уровень: Этот уровень отвечает за физическое соединение и передачу сигналов между физическими устройствами в сети. Примерами протоколов этого уровня являются Ethernet (802.3) и Wi-Fi (802.11), которые определяют спецификации структуры кабеля, схемы модуляции и форматы кадров.

- Канальный уровень: Этот уровень обеспечивает надежную передачу данных между соседними устройствами в сети. Примерами протоколов этого уровня являются Ethernet (IEEE 802.2) для локальных сетей и High Level Data Link Control (HDLC) для глобальных сетей.
- Сетевой уровень: этот уровень отвечает за маршрутизацию данных и управление сетевым трафиком. Примерами протоколов этого уровня являются Internet Protocol (IP) и Internet Control Message Protocol (ICMP), которые используются для маршрутизации и обработки пакетов данных через Интернет.
- Транспортный уровень: Этот уровень обеспечивает надежную передачу данных между конечными устройствами. Примерами протоколов этого уровня являются Transmission Control Protocol (TCP) и User Datagram Protocol (UDP), которые обеспечивают контроль и управление потоком передачи данных.
- Сеансовый уровень: Этот уровень управляет установлением, поддержанием и завершением сеансов связи между устройствами. Примером протокола этого уровня является протокол Secure Sockets Layer (SSL), который обеспечивает безопасное соединение между клиентами и серверами.
- Уровень представления: Этот уровень отвечает за преобразование и представление данных и обеспечивает согласованность формата данных между устройствами. Примерами протоколов этого уровня являются протоколы кодирования, сжатия, шифрования и форматирования данных.
- Прикладной уровень: этот уровень позволяет приложениям получать доступ к сети и обеспечивает взаимодействие между различными программами. Примерами протоколов этого уровня являются HTTP (Hypertext Transfer Protocol) для передачи веб-страниц, SMTP (Simple Mail Transfer Protocol) для передачи электронной почты и FTP (File Transfer Protocol) для передачи файлов.

PROFINET относится к категории протоколов промышленной автоматизации и работает на разных уровнях модели OSI. Он использует Ethernet на физическом и канальном уровнях для передачи данных и обеспечивает передачу данных в режиме реального времени, надежность и механизмы безопасности PROFINET также определяет собственные прикладные протоколы и службы для обеспечения обмена данными между промышленными устройствами и системами управления.

Важно отметить, что классификация протоколов может меняться в зависимости от контекста и используемой модели. Например, вместо модели OSI в промышленной автоматизации часто используется модель TCP/IP, которая объединяет несколько уровней OSI. TCP/IP - это сетевая модель для цифровой передачи данных. Она определяет, как данные должны формироваться в пакеты, обрабатываться, отправляться, направляться и получаться между разными сетями и хостами. Название TCP/IP образовано от двух ключевых протоколов семейства - Transmission Control Protocol (TCP) и Internet Protocol (IP). Модель TCP/IP обладает большей универсальностью и совместимостью, так как она поддерживает различные сетевые архитектуры и топологии. Модель TCP/IP имеет большую эффективность и производительность, так как она имеет меньше уровней и накладных расходов, чем модель OSI. Поэтому модель TCP/IP стала стандартом для работы интернета и большинства современных сетей.

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.004.png)

Рисунок 1.2 – сетевые уровни моделей OSI & TCP/IP

Промышленные протоколы играют важную роль в развитии индустриальной автоматизации и цифровизации производства. Они позволяют создавать сложные и гибкие системы управления, которые способны адаптироваться к изменяющимся условиям и требованиям. Они также способствуют повышению эффективности, безопасности и экологичности процессов производства. Промышленные протоколы постоянно совершенствуются и расширяют свои возможности благодаря интеграции с новыми технологиями, такими как Интернет вещей (IoT), Искусственный интеллект (AI), Облачные вычисления (Cloud Computing) и др. Изучение промышленных протоколов позволяет получить ценные знания и навыки, которые могут быть применены в различных отраслях промышленности и сферах деятельности.

## 1.4 Анализ предметной области

Сетевые протоколы - это набор правил и соглашений, которые определяют, как обмениваться данными между различными устройствами и системами в сети. Сетевые протоколы устанавливают формат, структуру, скорость, последовательность и надежность передачи данных¹.

Выбор сетевого протокола важен при автоматизации производства, потому что он влияет на производительность, безопасность, совместимость и интероперабельность производственных устройств и систем.

Существует множество сетевых протоколов, которые используются для разных целей и задач в промышленной автоматизации. Некоторые из наиболее распространенных сетевых протоколов для автоматизации крупномасштабного производства:

**Common Industrial Protocol (CIP)** - это универсальный протокол прикладного уровня, который используется семейством промышленных сетей, таких как EtherNet/IP, ControlNet и DeviceNet. Он предоставляет комплекс сообщений и сервисов для широкого спектра промышленных приложений, включая управление, безопасность, энергию, синхронизацию и движение, информацию и управление сетью. Этот протокол обеспечивает интеграцию контроля с информацией, различными CIP-сетями и интернет-технологиями. Поддерживается сотнями поставщиков по всему миру и независим от физической среды передачи данных, CIP предоставляет пользователям единую архитектуру связи на всем промышленном предприятии².

**PROFIBUS** - это открытый стандарт для обмена данными по промышленному шинному интерфейсу (RS-485 или оптоволокно). Он поддерживает различные типы коммуникации, такие как циклическая передача данных между контроллером и периферийными устройствами (PROFIBUS DP), ациклическая передача данных между контроллером и интеллектуальными устройствами (PROFIBUS PA) и передача данных между контроллерами (PROFIBUS FMS). Он также поддерживает различные типы данных, такие как цифровые, аналоговые, видео и аудио³.

**EtherCAT** - это высокоскоростной протокол для обмена данными по Ethernet. Он использует технологию "процессинга на лету", которая позволяет каждому устройству в сети читать или записывать данные из или в поток данных во время его прохождения через устройство. Это позволяет достигать высокой скорости передачи данных (до 100 Мбит/с) и низкой задержки (менее 1 мкс). Он также поддерживает различные типы коммуникации, такие как циклическая передача данных для управления движением и измерениями (EtherCAT Cyclic), а циклическая передача данных для конфигурации и диагностики (EtherCAT Acyclic).

**Modbus** - это простой и универсальный протокол для обмена данными по последовательному интерфейсу (RS-232, RS-485 или оптоволокно). Он использует технологию “запрос-ответ”, которая позволяет мастеру отправлять запросы на чтение или запись данных к одному или нескольким устройствам, которые отвечают данными или подтверждением. Он поддерживает различные типы данных, такие как цифровые, аналоговые, регистры и счетчики.

**OPC UA** - это открытый стандарт для обмена данными по промышленному Ethernet. Он предоставляет единую архитектуру связи для различных промышленных приложений, включая управление, информацию, безопасность, аналитику и облачные сервисы. Он использует технологию “публикация-подписка”, которая позволяет устройствам и системам публиковать свои данные в сети и подписываться на данные других устройств и систем. Он поддерживает различные типы данных, такие как цифровые, аналоговые, видео, аудио и т.д., а также различные режимы работы, такие как циклический, ациклический, событийный и т.д…

**PROFINET** — это открытый промышленный стандарт для автоматизации от ассоциации Ethernet PROFIBUS & PROFINET International (PI). PROFINET использует TCP / IP и IT - стандарты, и режим реального времени Ethernet. Концепция PROFINET имеет модульную структуру, при помощи которой пользователи могут выбрать каскадирование самих функций. Они существенно отличаются в зависимости от типа обмена данными для выполнения отчасти очень высоких требований к скорости.

## 1.5 Обоснование разработки

Обоснование и потенциальные преимущества разработки модуля протокола PROFINET для управляющей программы ptusa\_main

Разработка модуля протокола PROFINET для управляющей программы ptusa\_main имеет ряд преимуществ, которые могут повысить функциональность и эффективность системы автоматизации производства. Некоторые из этих преимуществ включают в себя:

- ` `Расширение возможностей и функциональности: Поддержка протокола PROFINET в программе управления ptusa\_main позволяет системе взаимодействовать с промышленными устройствами, поддерживающими этот протокол. Это дает возможность не только мониторить устройства, управлять ими и собирать данные, но и обмениваться информацией в режиме реального времени, что способствует более точному и эффективному управлению производственными процессами.
- ` `Улучшенная совместимость и интеграция: PROFINET является одним из лидирующих протоколов в области промышленной автоматизации и широко используется во многих отраслях промышленности. Интеграция модуля PROFINET в ptusa\_main позволяет программе управления использовать PROFINET для связи с различными системами, машинами и устройствами, поддерживающими этот протокол. Это облегчает интеграцию и взаимодействие с другими компонентами полевой шины, упрощает обмен данными и повышает общую эффективность системы.
- ` `Повышение производительности и эффективности: Использование PROFINET в программе управления может повысить производительность и эффективность производственных процессов. PROFINET позволяет обмениваться данными в режиме реального времени и быстро реагировать на изменения благодаря высокой пропускной способности и малому времени отклика. Это особенно важно для промышленных систем, требующих точного управления, синхронизации и мониторинга процессов.
- ` `Упрощенная установка и обслуживание: PROFINET имеет простой и интуитивно понятный интерфейс, который упрощает установку и обслуживание промышленных сетей. Модуль PROFINET в программе управления ptusa\_main позволяет конфигурировать сеть, настраивать устройства и диагностировать проблемы сети с помощью стандартизированных методов и инструментов. Это сокращает время, необходимое для установки и конфигурирования системы, и упрощает обслуживание в процессе эксплуатации.
- ` `Снижение затрат на оборудование и инфраструктуру: Поскольку PROFINET основан на Ethernet, можно использовать существующую сетевую инфраструктуру, такую как кабели Ethernet, коммутаторы и маршрутизаторы. Это снижает стоимость дополнительного сетевого оборудования и упрощает развертывание промышленных сетей. Таким образом, разработка модуля для взаимодействия управляющей программы производства с оборудованием по протоколу PROFINET является актуальной и необходимой задачей, которая будет способствовать повышению эффективности и гибкости производственных процессов, улучшению контроля и автоматизации, а также сокращению времени простоя и затрат на обслуживание оборудования.
##  1.6 Постановка задачи
Целью данного дипломного проекта является разработка и внедрение модуля протокола PROFINET для программы управления ptusa\_main для улучшения функциональности, интеграции и эффективности производственных процессов. В рамках проекта будут решены следующие задачи

Разработка модуля PROFINET: Для управляющей программы ptusa\_main должен быть разработан и внедрен модуль, поддерживающий протокол PROFINET. Модуль должен быть способен взаимодействовать с промышленными устройствами, поддерживающими протокол PROFINET, и обмениваться данными в режиме реального времени.

Интеграция в существующие системы: Модуль должен быть интегрирован в существующую программу управления ptusa\_main, сохраняя совместимость и функциональность других компонентов программы. Это позволит увеличить функциональность системы и обеспечить более гибкое и эффективное взаимодействие с промышленным оборудованием.

Тестирование и валидация: разработанные модули должны быть тщательно протестированы и валидны. Сюда входит тестирование совместимости с различным оборудованием, проверка стабильности и надежности передачи данных по сети PROFINET и обеспечение соответствия стандартам и требованиям промышленной автоматизации.

Оценка эффективности и преимуществ В данном дипломном проекте будет проведена оценка эффективности модуля PROFINET. Сюда входит оценка функциональности и возможностей системы, повышение производительности и эффективности производственных процессов, а также снижение затрат на оборудование и техническое обслуживание.

Рассмотрев эти темы, можно сделать следующие выводы:

- Улучшение функциональности системы управления: Разработанный модуль может расширить функциональность управляющей программы ptusa\_main за счет поддержки протокола PROFINET. Это обеспечивает более гибкое управление и контроль производственных процессов, мониторинг и сбор данных с промышленного оборудования, а также связь с промышленным оборудованием в режиме реального времени.
- Расширенное взаимодействие с промышленными устройствами Модуль протокола PROFINET обеспечивает более глубокое взаимодействие между управляющей программой ptusa\_main и различными промышленными устройствами, поддерживающими этот протокол. Это делает связь и обмен данными с контроллерами, датчиками, исполнительными механизмами и другими устройствами более эффективными и повышает гибкость и универсальность системы управления.
- Повышение производительности и эффективности: Интеграция PROFINET в управляющее программное обеспечение повышает производительность и эффективность производственных процессов: PROFINET обеспечивает связь в реальном времени благодаря высокой пропускной способности и короткому времени отклика, что позволяет процессам адаптироваться к изменениям. Это обеспечивает более надежное управление и мониторинг производственных операций и повышает надежность и безопасность системы.
- Сокращение времени установки и обслуживания: Время установки и технического обслуживания может быть сокращено благодаря использованию PROFINET и интерфейсных модулей PROFINET PROFINET предоставляет стандартизированные методы и средства для настройки параметров сети, диагностики и конфигурации оборудования. Методы и инструменты для настройки параметров сети, диагностики и конфигурации оборудования. Это упрощает процесс установки, монтажа и технического обслуживания, экономит время и повышает производительность труда персонала.

В результате интерфейсный модуль PROFINET для управляющего ПО ptusa\_main помогает оптимизировать производственные процессы, улучшить управление и интеграцию с промышленным оборудованием и снизить затраты на оборудование и обслуживание. Это, в свою очередь, помогает компаниям в области промышленной автоматизации повысить свою производительность и конкурентоспособность. Разработанные модули позволяют более точно и быстро контролировать производственные процессы, сокращают время реакции на изменения и улучшают координацию между различным оборудованием и системами. Разработанный модуль протокола PROFINET и его интеграция в управляющее программное обеспечение "ptusa\_main" обеспечивают следующие преимущества:

- Повышенная гибкость и масштабируемость: Протокол PROFINET обеспечивает гибкость в выборе и интеграции полевых устройств, позволяя работать с различными типами и моделями оборудования. Это позволяет предприятиям легко адаптироваться к изменениям в производственных процессах и расширять систему по мере необходимости.
- Более точное и оперативное управление: Протокол PROFINET обеспечивает передачу данных в режиме реального времени, что позволяет быстро получать информацию о состоянии процесса, показания датчиков и управлять исполнительными механизмами. Это повышает точность и надежность управления производственными операциями.
- Экономия времени и упрощение технического обслуживания: стандартизированные методы и инструменты PROFINET упрощают установку, конфигурирование и диагностику системы. Это сокращает время установки и обслуживания и упрощает обучение.
- Экономическая эффективность: Поскольку PROFINET может использовать существующую сетевую инфраструктуру на базе Ethernet, внедрение разработанных модулей снижает затраты на дополнительное сетевое оборудование. Это экономически эффективное решение, которое помогает предприятиям экономить бюджет и ресурсы.

В заключение следует отметить, что разработка модуля протокола PROFINET для управляющего программного обеспечения ptusa\_main позволит повысить эффективность производства, улучшить координацию и управление процессом.

## 2 ПРОЕКТИРОВАНИЕ СИСТЕМЫ

##   2.1 Обзор и анализ существующих решений по теме
Существуют различные аппаратные и программные платформы, предлагающие решения для протокола PROFINET. Некоторые из них рассмотрены и проанализированы здесь:

- Siemens SIMATIC: Siemens предлагает семейство продуктов SIMATIC, которое включает контроллеры, устройства ввода/вывода и программное обеспечение, работающие с PROFINET SIMATIC является одним из наиболее распространенных и широко используемых решений в промышленной автоматизации. Контроллеры SIMATIC имеют встроенный интерфейс PROFINET для простой интеграции протоколов и высокой производительности.
- Beckhoff TwinCAT: TwinCAT - это программно-аппаратная платформа, разработанная компанией Beckhoff. Состоящая из программного обеспечения для управления и мониторинга процессов, терминалов ввода-вывода, промышленных ПК и других компонентов, TwinCAT поддерживает протокол PROFINET и предлагает гибкие и масштабируемые решения для автоматизации.
- Phoenix Contact PLCnext: PLCnext - это программно-аппаратная платформа, разработанная компанией Phoenix Contact. Она включает в себя контроллеры, модули ввода/вывода, программное обеспечение для управления процессами и мониторинга. Платформа поддерживает PROFINET и обеспечивает гибкую конфигурацию и интеграцию с другими системами.
- B&R Automation Studio: Automation Studio от B&R Automation - это универсальное программное обеспечение для автоматизации процессов, которое поддерживает PROFINET и предоставляет широкий набор инструментов для разработки и управления системами автоматизации. B&R Automation Studio может работать на широком спектре контроллеров и платформ, обеспечивая гибкость и адаптивность при выборе оборудования.

Каждая из этих программно-аппаратных платформ имеет свои особенности и преимущества. Они предлагают различные возможности для работы с PROFINET, такие как различные типы устройств, конфигурация сети и поддержка связи в реальном времени.

Одним из основных различий между решениями является производительность и масштабируемость. Siemens SIMATIC предлагает широкий спектр контроллеров, включая высокопроизводительные модели, способные обрабатывать большие объемы данных и обеспечивать быструю связь. Кроме того, TwinCAT от Beckhoff славится своей высокой производительностью и горизонтальной масштабируемостью, что позволяет расширять систему по мере необходимости.

Гибкость и простота использования также важны: Beckhoff TwinCAT и Phoenix Contact PLCnext предлагают программное обеспечение для гибкой конфигурации и интеграции с другими системами, позволяя пользователям настраивать и адаптировать систему к своим конкретным потребностям. Siemens SIMATIC и B&R Automation Studio также предоставляют ряд инструментов и ресурсов для разработки систем и управления.

В дополнение к этим аппаратным и программным платформам также доступны следующие решения для PROFINET:

- Omron Sysmac: Интегрированная платформа автоматизации от компании Omron. Omron Sysmac поддерживает PROFINET и обеспечивает высокую производительность, гибкость и надежность в сетевой среде.
- Rockwell Automation Allen-Bradley: Allen-Bradley - один из ведущих производителей средств промышленной автоматизации. Она предлагает контроллеры и программное обеспечение, включая интегрированную платформу Studio 5000. Платформа поддерживает протоколы Ethernet/IP и PROFINET и обеспечивает комплексную интеграцию устройств и возможности управления в промышленных сетях.
- ABB AC500: AC500 - это линейка программируемых логических контроллеров (ПЛК) компании АББ, поддерживающих протокол PROFINET и предоставляющих гибкие и масштабируемые решения для промышленной автоматизации, средства разработки и инструменты для программирования и конфигурирования системы.

Каждое из этих решений имеет свои уникальные особенности и преимущества. При выборе конкретного решения важно учитывать производственные требования, бюджет, гибкость конфигурации и поддержку поставщика. Также следует учитывать совместимость с существующей инфраструктурой и возможность интеграции с другими системами автоматизации, используемыми в компании.

## 2.2 Обоснование выбора программно-аппаратной платформы

Программно-аппаратная платформа — это совокупность программных и аппаратных средств, которые обеспечивают функционирование и разработку приложений для автоматизации производства. Выбор подходящей платформы имеет большое значение для успешной реализации и поддержки автоматизированных систем, так как от этого зависят:

- Скорость и качество разработки приложений
- Совместимость и интеграция с различными устройствами и системами
- Масштабируемость и гибкость решений
- Надежность и безопасность работы
- Стоимость владения и эксплуатации

Гибкость и масштабируемость: PLCNext предлагает гибкое и модульное решение для автоматизации производства. Можно интегрировать различные типы устройств и модулей ввода/вывода, что позволяет адаптировать систему к конкретным требованиям предприятия. Это особенно полезно, когда в будущем необходимо интегрировать различные компоненты и расширить их функциональность.

- Открытая архитектура и экосистема: PLCNext основан на открытой архитектуре и поддерживает различные языки программирования, включая IEC 61131-3, C++, C# и Python. Это обеспечивает разработчикам гибкость и свободу выбора, позволяя им использовать знакомые инструменты и языки программирования для разработки приложений. Кроме того, PLCNext имеет активное сообщество разработчиков и регулярно пополняется новыми функциями.
- Простота использования и конфигурирования: PLCNext предлагает интуитивно понятный пользовательский интерфейс и инструменты для конфигурирования и программирования. Это упрощает процесс разработки и интеграции систем автоматизации, что особенно важно в проектах, где время и ресурсы ограничены.
- Поддержка протокола PROFINET: PLCNext поддерживает протокол PROFINET, что позволяет интегрировать устройства и компоненты, работающие в этом стандарте PROFINET - это протокол, широко используемый в промышленной автоматизации. Он облегчает интеграцию систем PLCNext с другими устройствами в существующих инфраструктурах и сетях.
- Расширенные функции обработки и анализа данных: PLCNext включает в себя функции обработки и анализа данных в контроллере и позволяет выполнять расширенные расчеты и анализ данных непосредственно на уровне устройства. Это полезно, например, для внедрения различных алгоритмов или оптимизации производственных процессов.

Общие причины выбора аппаратно-программной платформы PLCNext для внедрения модулей протокола PROFINET можно сформулировать следующим образом:

- Совместимость с PROFINET: PLCNext поддерживает протокол PROFINET, широко признанный стандарт в промышленной автоматизации. Это позволяет устройствам, использующим данный протокол, эффективно интегрироваться и взаимодействовать друг с другом. Таким образом, выбор PLCNext обеспечивает совместимость с существующими инфраструктурами и оборудованием, использующим протокол PROFINET.
- Гибкость и масштабируемость: PLCNext предлагает гибкое модульное решение, которое позволяет адаптировать систему автоматизации к конкретным потребностям вашего производственного предприятия. Благодаря возможности интеграции различных типов устройств и модулей ввода/вывода, PLCNext обладает гибкостью и масштабируемостью, что позволяет адаптировать систему к конкретным требованиям проекта.
- Открытая архитектура и различные языки программирования: PLCNext основан на открытой архитектуре, которая позволяет свободно выбирать языки программирования и средства разработки, включая IEC 61131-3, C++, C# и Python. Это позволяет разработчикам использовать знакомые им инструменты и выбирать язык, который лучше всего подходит для интерфейса PROFINET.
- Простота использования и конфигурирования: PLCNext предоставляет интуитивно понятный пользовательский интерфейс и инструменты для конфигурирования и программирования. Это упрощает разработку и интеграцию систем автоматизации, сокращает время конфигурирования и повышает производительность разработчиков.

Расширенные функции обработки и анализа данных: PLCNext предоставляет функции обработки и анализа данных на уровне контроллера. Это позволяет выполнять сложные вычисления и анализ данных непосредственно на уровне устройства, помогая реализовать алгоритмы оптимизации процессов и повысить эффективность системы. Расширенные функции обработки данных позволяют анализировать и обрабатывать данные в режиме реального времени, принимать обоснованные управленческие решения и оптимизировать производственные процессы. Активное сообщество разработчиков и поддержка поставщиков: PLCNext имеет активное сообщество разработчиков, которое обменивается опытом, предоставляет ресурсы и поддержку. Это дает вам доступ к дополнительной документации, примерам кода и решениям, которые помогут вам в разработке модулей протокола PROFINET. Кроме того, производители PLCNext гарантируют стабильность и надежность системы, предоставляя поддержку и обновления аппаратного и программного обеспечения.

В заключение следует отметить, что выбор программно-аппаратной платформы PLCNext обоснован ее совместимостью с протоколом PROFINET, гибкостью и масштабируемостью, открытой архитектурой и разнообразием языков программирования, простотой использования и конфигурирования, а также расширенными возможностями обработки данных и поддержкой сообщества разработчиков, обоснованной поддержкой производителей. В совокупности эти факторы обеспечивают эффективность и успех дипломных проектов, в рамках которых разрабатываются модули на базе PROFINET.
## 2.3   Аппаратная часть 
Аппаратное обеспечение, выбранное для разработки модуля протокола PROFINET, включает в себя PLCNext StarterKit и контроллер AXC F 2152. Ниже приведены основные характеристики и компоненты этой аппаратной платформы:

PLCNext StarterKit: PLCNext StarterKit - это комплект, содержащий все необходимое для начала работы с контроллерами PLCNext, включая контроллер AXC F 2152. Он обеспечивает базовую платформу, необходимую для разработки и тестирования приложений автоматизации.

Контроллер AXC F 2152 - это контроллер для системы ввода-вывода Axioline F. Он предназначен для прямого управления модулями ввода-вывода Axioline F(система ввода-вывода в реальном времени от Phoenix Contact. Она предназначена для использования в жестких промышленных условиях и обеспечивает быстрое и простое подключение модулей ввода-вывода.) [Система Axioline F имеет множество функций и возможностей, таких как измерение тока и напряжения](https://www.sea.com.ua/ua/elektrotehnicheskaya-produktsiya/news/sistema-vvoda-vyvoda-axioline-f-dla-umnyh-podstancij-i-asu-tp/) и имеет два интерфейса Ethernet. [Контроллер был разработан для обеспечения максимальной производительности и простоты использования в жестких промышленных условиях](https://www.phoenixcontact.com/ru-pc/produkty/kontroller-axc-f-2152-2404267).

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.005.png)

Рисунок 2.1 - PLCNext-Technology

Процессор: контроллер AXC F 2152 оснащен мощным процессором ARM Cortex-A9 для высокой производительности и быстрой обработки данных.

Контроллеры AXC F 2152 обладают следующими возможностями:

•	Может быть установлено до 63 модулей ввода-вывода AXIO;

•	Подключение по Ethernet;

•	Поддерживаются многочисленные протоколы, такие как: http, https, FTP, OPC UA, SNTP, SNMP, SMTP, SQL, MySQL, DCP и т.д;

•	Подключение к хранилищу PLCnext;

•	2 интерфейса Ethernet (встроенный коммутатор);

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.006.png)

Рисунок 2.2 –технические характеристики контроллера AXC F 2152

Контроллер AXC F 2152 имеет следующие технические характеристики:

•	Ширина: 45 мм

•	Высота: 126,93 мм

•	Глубина: 75 мм

•	Степень защиты: IP20

Память: контроллер имеет достаточный объем встроенной памяти для хранения программ и данных.

Расширяемость: Контроллер может быть расширен путем добавления модулей ввода/вывода и плат расширения, что позволяет адаптировать систему к потребностям проекта.

Для подключения различной периферии к контроллеру AXC F 2152 вам необходимо:

1\.	Использовать модуль базовой шины для соединения контроллера с локальной шиной Axioline F, к которой можно подключить до 63 устройств ввода-вывода.

2\.	Использовать два интерфейса Ethernet для подключения контроллера к сети PROFINET.

3\.	Настроить параметры сети и контроллера с помощью программы Startup.

4\.	Создать новый проект в программе PLCnext Engineer и добавить контроллер и периферийные устройства в конфигурацию оборудования.

5\.	Загрузить проект в контроллер и запустить его.

К контроллеру AXC F 2152 можно подключить различные устройства ввода-вывода системы Axioline F, такие как:

•	Цифровые модули ввода-вывода (например, DI8/1 DO8/1 2701916) для работы с дискретными сигналами. 

•	Аналоговые модули ввода-вывода (например, AI2 AO2 2702072) для работы с аналоговыми сигналами. 

•	Модули специального назначения (например, AXF BK PN 2701815) для подключения к другим шинам, таким как PROFINET.

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.007.png)

`      `Рисунок 2.3 – Компоненты контроллера AXC F 2152

Пояснение к рисунку:

- Базовый модуль шины;
- Модуль электроники;
- Кнопка сброса;
- Держатель SD-карты;
- Индикаторы диагностики и состояния;
- Интерфейс Ethernet (1), Интерфейс Ethernet (2);;
- Разъем для подключения напряжения питания

Топология: PLCNext поддерживает различные сетевые топологии, такие как звезда, линия и дерево, что позволяет гибко организовать сетевую инфраструктуру.

Дисплей: контроллер обеспечивает визуальную индикацию рабочего и диагностического состояния с помощью светодиодных дисплеев.

LED PWR - показывает наличие питания на контроллере.

LED RUN - показывает состояние работы контроллера.

LED ERR - показывает наличие ошибок в работе контроллера

LED ETH1 и LED ETH2 - показывают состояние соединения и активность на интерфейсах Ethernet.

LED SD - показывает состояние карты памяти SD, если она установлена.

LED USB - показывает состояние подключения к ПК через разъем USB C.

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.008.png)![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.009.png)

Рисунок 2.4 – Индикация контроллера AXC F 2152

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.010.png)![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.011.png)

`      `Рисунок 2.5 – Индикация контроллера AXC F 2152

Периферийные устройства: Контроллер AXC F 2152 поддерживает широкий спектр периферийных устройств, включая модули ввода/вывода, аналого-цифровые преобразователи (АЦП), цифро-аналоговые преобразователи (ЦАП) и интерфейсы для подключения датчиков, исполнительных механизмов и других устройств автоматизации. Поддержка. Это позволяет контроллеру взаимодействовать с реальным оборудованием для мониторинга и управления процессом.

Интеграция PROFINET: AXC F 2152 поддерживает PROFINET, обеспечивая подключение и связь с другими устройствами, соответствующими протоколу. Это открывает возможность интеграции с существующими устройствами и системами, использующими PROFINET, и позволяет разрабатывать приложения для мониторинга и управления этими устройствами.

Языки программирования: AXC F 2152 поддерживает различные языки программирования, включая IEC 61131-3, C++, C# и Python. Это позволяет разработчикам выбрать наиболее подходящий язык для реализации модуля протокола PROFINET и обеспечивает гибкость в разработке и настройке программного обеспечения.

Условия эксплуатации и хранения контроллера AXC F 2152 следующие:

Температура окружающей среды (эксплуатация): от -25 °C до +60 °C при высоте до 2000 м над уровнем моря (с учетом дерейтинга) или от -25 °C до +55 °C при высоте до 3000 м над уровнем моря (с учетом дерейтинга)123.

Температура окружающей среды (хранение/транспортировка):от-40°Cдо+85 °C.

Относительная влажность (эксплуатация): от 5 % до 95 % (в соответствии с DIN EN 61131-2)123.

Относительная влажность (хранение/транспортировка): от 5 % до 95 % (в соответствии с DIN EN 61131-2)123.

Атмосферное давление (эксплуатация): от 70 кПа до 106 кПа (до 3000 м над уровнем моря)123.

Атмосферное давление (хранение/транспортировка): от 58 кПа до 106 кПа (до 4500 м над уровнем моря)123.

Степень защиты: IP20123.

Класс защиты: III (IEC 61140, EN 61140, VDE 0140-1)123.

Удар: 30 g, период 11 мс, полусинусоидальный импульс, в соответствии с IEC 60068-2-27123.

Вибрация (эксплуатация): 5 g123.

Выбор аппаратно-программной платформы PLCNext StarterKit и контроллера AXC F 2152 обоснован совместимостью с протоколом PROFINET, мощностью и гибкостью контроллера, поддержкой различных периферийных устройств, возможностью интеграции существующих систем автоматизации и широким выбором языков программирования. Эти элементы обеспечивают эффективную и гибкую платформу для разработки и успешной интеграции модулей PROFINET в производственную среду.
## 2.4 Разбор принципа работы протокола Profinet
PROFINET - это Ethernet-базированный протокол для обмена данными между контроллерами и устройствами в сетях CC-Link. Он поддерживает различные режимы связи в реальном времени, такие как RT (Real Time) и IRT (Isochronous Real Time). RT использует эффективный протокол, который пропускает слои TCP/IP и обеспечивает быструю и детерминированную передачу данных. IRT использует дополнительные механизмы, такие как синхронизация часов, резервирование полосы пропускания и планирование кадров, чтобы обеспечить высокую скорость и минимальное дрожание передачи данных для высокопроизводительных приложений.

Обмен данными между узлами автоматизированной системы под управлением оборудования Siemens реализуется как по полевой шине, которая называется PROFIBUS, так и в промышленной сети PROFINET.

Шина PROFIBUS использует специальный двужильный кабель с разъемами DB-9. Для связи нескольких узлов разъем может соединять два кабеля. Также в нем есть переключатель для терминального резистора. Терминальный резистор должен быть включен на концевых устройствах сети, таким образом сообщается, что это первое или последнее устройство, а после него уже ничего нет, только мрак и пустота (все rs485 так работают). Если на промежуточном разъеме включить резистор, то следующий за ним участок будет отключен.

![https://habrastorage.org/r/w1560/webt/e3/vk/sa/e3vksaqjxtquusklwzvesofi3z0.jpeg](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.012.jpeg)

`      `Рисунок 2.6 – Кабель PROFIBUS с соединительными разъемами.

В сети PROFINET используется аналог витой пары, как правило, с разъемами RJ-45, кабель окрашен в зеленый цвет. Если топология PROFIBUS —шина, то топология сети PROFINET может представлять собой: кольцо, звезду, дерево, итд. Однако рекомендуется использовать топологию сети типа «дерево» или «звезда».

![https://habrastorage.org/r/w1560/webt/xy/tl/yp/xytlypvc4izpkzr4gyaqipaildi.jpeg](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.013.jpeg)

`      `Рисунок 2.7 – Контроллер Siemens с подключенным кабелем PROFINET. 

Цикл передачи PROFINET идентичен циклу передачи Ethernet. 25-й и 26-й байты являются идентификаторами типа передаваемых данных — PROFINET. Далее следует блок информации, специфичной для PROFINET, а завершается телеграмма стандартным для Ethernet проверочным блоком FCS. Таким образом, с точки зрения коммутатора Ethernet, телеграмма PROFINET — это просто некие специфические данные, передаваемые через компьютерную сеть. И они могут обрабатываться точно так же, как и любые другие.


![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.014.jpeg)

Рисунок 2.8 – Структура Ethernet- и PROFINET-телеграмм

При этом приблизительно 50% трафика в PROFINET зарезервировано под обычную передачу данных (размер этой доли может регулироваться путем установки соответствующих настроек), для которой не важна точная привязка по времени. Обычно это передача данных по протоколу TCP/IP. Остальной трафик используется для передачи информации в реальном времени (Real-Time — RT) с задержкой порядка единиц-десятков миллисекунд, а также в изохронном реальном времени (Isochronous Real-Time — IRT), когда задержка составляет менее 1 мс.

Существуют несколько протоколов обмена в сети PROFINET:

- PROFINET IO;
- PROFINET CBA.

Протокол PROFINET IO делится на несколько классов:

- PROFINET NRT (без реального времени) — используется в приложениях, где временные параметры не критичны. В нем используется протокол передачи данных Ethernet TCP/IP, а также UDP/IP.
- PROFINET RT (реальное время) — тут обмен данными ввода/вывода реализован с помощью фреймов Ethernet, но диагностические данные и данные связи все еще передаются через UDP/IP. 
- PROFINET IRT (изохронное реальное время) — этот протокол был разработан специально для приложений управления движением и включает в себя изохронную фазу передачи данных.

Передача IRT осуществляется для подсистем ввода-вывода, иначе именуемых IO-подсистемами. В PROFINET различают следующие типы IO-оборудования:

- IO-контроллер. Осуществляет обмен информацией с полевыми устройствами, а также доступ к IO-сигналам через область процесса.
- IO-устройство. Полевое устройство, назначенное определенному IO-контроллеру.
- IO-супервизор. Осуществляет диагностику, а также интерфейс «человек-машина» (HMI). В большинстве случаев представляет собой некую консоль, с которой можно проконтролировать работу оборудования и сделать необходимые настройки.

Что касается реализации протокола жесткого реального времени PROFINET IRT, то для коммуникаций с удаленными устройствами в нем выделяют два канала обмена: изохронный и асинхронный. Изохронный канал с фиксированной по времени длиной цикла обмена использует тактовую синхронизацию и передает критичные ко времени данные, для передачи используются телеграммы второго уровня. Длительность передачи в изохронном канале не превышает 1 миллисекунду.

![Рис. 2. Резервирование пропускной способности](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.015.jpeg)

Рисунок 2.9 – Резервирование пропускной способности

В асинхронном канале передаются так называемые real-time-данные, которые тоже адресуются посредством MAC-адреса. Дополнительно передается различная диагностическая и вспомогательная информация уже поверх TCP/IP. Ни real-time-данные, ни тем более другая информация, разумеется, не может прерывать изохронный цикл.

Расширенный набор функций PROFINET IO нужен далеко не для каждой системы промышленной автоматики, поэтому этот протокол масштабируют под конкретный проект, с учетом классов соответствия или классов применения (conformance classes): СС-A, CC-B, CC-CC. Классы соответствия позволяют выбрать полевые устройства и магистральные компоненты с минимально необходимой функциональностью.

![https://habrastorage.org/r/w1560/webt/q-/q0/ix/q-q0ixd0j9x0wl7uhrs4mwqcpf0.png](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.016.png)

`      `Рисунок 2.10 – Классы соответствия.

Второй протокол обмена в сети PROFINET — PROFINET CBA — служит для организации промышленной связи между оборудованием различных производителей. Основной производственной единицей в системах СВА является некая сущность, которая называется компонентом. Этот компонент обычно представляет собой совокупность механической, электрической и электронной части устройства или установки, а также соответствующее прикладное программное обеспечение. Для каждого компонента выбирается программный модуль, который содержит полное описание интерфейса данного компонента по требованиям стандарта PROFINET. После чего эти программные модули используются для обмена данными с устройствами.

PROFINET имеет множество профилей, которые определяют дополнительные функции и требования для различных областей применения. Например, профиль PROFIsafe описывает механизмы для обеспечения безопасности в сетях PROFINET. Профиль PROFIdrive определяет интерфейс для приводов и двигателей. Профиль PROFIenergy регулирует потребление энергии в сетях PROFINET. Существует множество профилей PROFINET для разных отраслей и приложений, таких как процессная автоматизация, интеграция сетей PROFIBUS, подключение интеллектуальных датчиков и исполнительных устройств и т.д.

Некоторые профили PROFINET также поддерживают технологию Time Sensitive Networking (TSN), которая обеспечивает управление и приоритизацию потоков данных в сетях Ethernet. TSN состоит из нескольких международных стандартов, таких как IEEE802.1AS (который определяет метод синхронизации часов), IEEE802.1Qbv (который определяет метод разделения времени) и другие. Эти стандарты позволяют гарантировать передачу данных в заданный период времени и совместную работу с другими протоколами. Например, CC-Link IE TSN - это стандарт для автоматизации, который сочетает в себе технологию TSN с протоколом CC-Link IE. Он поддерживает гигабитную скорость передачи данных и изохронный режим реального времени (IRT) для высокопроизводительных приложений. Он также позволяет интегрировать другие протоколы, такие как PROFINET, EtherCAT и OPC UA, а также стандартные устройства Ethernet, такие как видеокамеры или беспроводные маршрутизаторы.

Для управления и мониторинга устройств в IP-сетях часто используется протокол SNMP (Simple Network Management Protocol). Это прикладной протокол, который определен IETF как часть набора стандартов для сетевого управления. SNMP позволяет собирать и организовывать информацию об управляемых устройствах и изменять эту информацию для изменения поведения устройств. Устройства, которые обычно поддерживают SNMP, включают кабельные модемы, маршрутизаторы, коммутаторы, серверы, рабочие станции, принтеры и другие.

SNMP работает по следующему принципу: один или несколько административных компьютеров (называемых менеджерами) выполняют отслеживание или управление группой хостов или устройств в компьютерной сети. На каждой управляемой системе есть постоянно запущенная программа (называемая агентом), которая передает информацию по SNMP менеджеру. Агент имеет локальное знание информации об управлении и переводит ее в специфическую для SNMP форму или из нее.

SNMP имеет три основных версии: SNMPv1, SNMPv2c и SNMPv3. Они отличаются по производительности, гибкости и безопасности. SNMPv1 - это оригинальная версия протокола. SNMPv2c - это расширение SNMPv1 с добавлением новых возможностей и типов данных. SNMPv3 - это дальнейшее расширение SNMPv2c с добавлением механизмов аутентификации, шифрования и контроля доступа.

## 2.5 Выбор средств реализации

Автоматизация производства — это процесс, при котором человеческое участие в управлении и контроле производственных процессов заменяется или минимизируется с помощью специального программного обеспечения и аппаратуры. Автоматизация производства имеет множество преимуществ, таких как повышение производительности, качества, безопасности, экономии ресурсов и снижение затрат. Однако, для успешной реализации и поддержки автоматизированных систем, необходимо выбрать подходящие средства реализации для разработки программного обеспечения. Средства реализации — это совокупность программных и аппаратных средств, которые обеспечивают функционирование и разработку приложений для автоматизации производства. Выбор подходящих средств реализации имеет большое значение для успешной реализации и поддержки автоматизированных систем, так как от этого зависят:

- ` `Скорость и качество разработки приложений
- ` `Совместимость и интеграция с различными устройствами и системами
- ` `Масштабируемость и гибкость решений
- ` `Надежность и безопасность работы
- ` `Стоимость владения и эксплуатации

В качестве средств реализации для разработки программного обеспечения для автоматизации производства были выбраны: Visual Studio Community и PLC Toolchain. 

**Visual Studio Community** — это бесплатная, полнофункциональная и расширяемая среда разработки (IDE) для создания современных приложений для разных платформ, включая Android, iOS, Windows, веб и облако. Visual Studio Community имеет следующие преимущества:

- Поддержка разных языков программирования, включая IEC 61131-3, C/C++, C#, Python и др.
- Возможность использования различных протоколов обмена данными, таких как PROFINET, Modbus, EtherCAT, CANopen, OPC UA и др.
- Наличие готовых бизнес-решений для разных направлений деятельности, таких как договорная работа, делопроизводство, бухгалтерия, HR-служба и др.
- Интеграция с облачными сервисами и платформами для аналитики, отчетности и управления данными.
- Высокая производительность, надежность и безопасность работы.

PLC Toolchain — это комплекс инструментов для разработки программного обеспечения для контроллеров на базе CODESYS Control Runtime System. PLC Toolchain имеет следующие преимущества:

- Позволяет адаптировать CODESYS Control Runtime System к разным платформам и требованиям
- Поддерживает разные 32- и 64-битные CPU платформы (CISC/RISC)
- Обеспечивает исполнение и отладку программированного кода IEC 61131-3
- Интегрируется с Visual Studio Community для удобной разработки и тестирования приложений
- Включает в себя документацию по интеграции и адаптации к целевому устройству
- Содержит примеры драйверов I/O и библиотек в виде исходного кода

Таким образом, выбор Visual Studio Community и PLC Toolchain может быть обоснован тем, что эти средства реализации предоставляют широкие возможности для разработки программного обеспечения для автоматизации производства, адаптируясь к разным требованиям и условиям.















## 3 РЕАЛИЗАЦИЯ И ИСПЫТАНИЕ СИСТЕМЫ
   ## 3.1 Реализация системы

Принцип работы моей разработки заключается в следующем:

Моя программа работает как мастер в сети profinet, то есть инициирует и контролирует обмен данными с устройствами (поставщиками данных). Программа принимает один аргумент командной строки - имя интерфейса Ethernet, на котором работает сеть PROFINET. Имя интерфейса Ethernet может быть задано в виде имени устройства (например, eth0) или в виде MAC-адреса (например, 00:11:22:33:44:55).

Программа инициализирует сеть profinet на заданном интерфейсе, создавая дескриптор сети и устанавливая параметры мастера. Дескриптор сети - это указатель на структуру pn\_handle\_t, которая содержит информацию о сети profinet, такую как имя станции, тип устройства, роль, идентификаторы, версии, IP-адрес и т.д… Параметры мастера задаются с помощью функций pn\_set\_\*, которые принимают дескриптор сети и значение параметра в качестве аргументов. Параметры мастера должны соответствовать спецификации протокола PROFINET. Программа также проверяет наличие ошибок при создании и настройке дескриптора сети, используя функцию pn\_errno. Функция pn\_errno возвращает код ошибки, а функция pn\_strerror возвращает строку с описанием ошибки. Если произошла ошибка, программа выводит сообщение об ошибке на стандартный поток ошибок и завершает работу с ненулевым кодом возврата.

Программа также проверяет устройства в сети PROFINET, получая информацию об устройствах и выводя ее на экран. Устройства в сети PROFINET представлены структурами pn\_device\_t, которые содержат информацию об устройствах, такую как дескриптор устройства, номер слота, номер подслота, идентификаторы, API, MAC-адрес, IP-адрес, имя и т.д… Дескриптор устройства - это указатель на структуру pn\_device\_handle\_t, которая используется для идентификации и управления устройством. Моя программа получает количество устройств в сети с помощью функции pn\_get\_device\_count, которая возвращает целое число, а также проверяет наличие ошибок при получении количества устройств. Если количество устройств изменилось по сравнению с предыдущим циклом работы программы - программа заполняет массив devices структурами pn\_device\_t, используя функцию pn\_get\_device\_info\_by\_index, которая принимает дескриптор сети и индекс устройства в качестве аргументов и заполняет указатели на структуры pn\_device\_t в качестве аргументов. Моя программа также проверяет наличие ошибок при получении информации об устройствах, выводит информацию об устройствах на экран, используя функцию printf и форматированные строки. Также, моя программа устанавливает параметры обмена данными для каждого устройства, используя функции pn\_set\_io\_data\_\*, которые принимают дескриптор сети, дескриптор устройства и значение параметра в качестве аргументов. Параметры обмена данными задаются в соответствии со спецификацией протокола PROFINET. Программа также проверяет наличие ошибок при установке параметров обмена данными, запускает обмен данными для каждого устройства, используя функцию pn\_start\_io\_data, которая принимает дескриптор сети и дескриптор устройства в качестве аргументов. Также проверяет наличие ошибок при запуске обмена данными и выводит состояние устройств на экран, используя функцию pn\_get\_device\_state, которая принимает дескриптор сети и дескриптор устройства в качестве аргументов и возвращает целое число, соответствующее одному из трех возможных состояний: PN\_DEVICE\_STATE\_OFFLINE (устройство не подключено к сети), PN\_DEVICE\_STATE\_ONLINE (устройство подключено к сети, но не готово к обмену данными) или PN\_DEVICE\_STATE\_OPERATE (устройство подключено к сети и готово к обмену данными). Помимо прочего, программа проверяет наличие ошибок при получении состояния устройств.

Программа способна обмениваться данными с устройствами в сети PROFINET. Данные представляют собой байтовые массивы фиксированного размера (DATA\_SIZE), которые передаются между мастером и устройствами по протоколу RT или IRT. 

Моя программа проверяет наличие новых входных данных для каждого устройства, используя функцию pn\_has\_new\_input\_data, которая принимает дескриптор сети и дескриптор устройства в качестве аргументов и возвращает целое число, которое равно 0, если нет новых входных данных, или больше 0, если есть новые входные данные. Моя программа также проверяет наличие ошибок при проверке новых входных данных. Если есть новые входные данные - программа читает их в буфер data\_buffer, используя функцию pn\_read\_input\_data, которая принимает дескриптор сети, дескриптор устройства, указатель на буфер и размер буфера в качестве аргументов и возвращает количество прочитанных байт. Программа также проверяет наличие ошибок при чтении входных данных, выводит принятые данные на экран, используя функцию printf и форматированные строки. Затем программа инвертирует каждый байт в буфере data\_buffer и отправляет его обратно в качестве выходных данных, используя функцию pn\_write\_output\_data, которая принимает дескриптор сети, дескриптор устройства, указатель на буфер и размер буфера в качестве аргументов и возвращает количество отправленных байт. Программа проверяет наличие ошибок при отправке выходных данных, выводит отправленные данные на экран, используя функцию printf и форматированные строки и использует мьютекс data\_mutex для синхронизации доступа к буферу данных.

Моя программа отправляет сигналы DC Latch на устройства в сети PROFINET. DC Latch - это специальный механизм для синхронизации времени между мастером и устройствами. DC Latch состоит из двух частей: DC Latch Frame и DC Latch Signal. DC Latch Frame - это кадр данных фиксированного размера (DC\_LATCH\_SIZE), который передается между мастером и устройствами по протоколу IRT. DC Latch Signal - это сигнал, который генерируется мастером и передается по физической линии Ethernet на все устройства одновременно. Сигнал служит для синхронизации времени отправки и приема кадров DC Latch. Программа заполняет буфер dc\_latch\_buffer случайными значениями, используя функцию rand(), которая возвращает целое число в диапазоне от 0 до 255. Затем выводит сгенерированный кадр DC Latch на экран, используя функцию printf и форматированные строки. После чего отправляет кадр DC Latch на каждое устройство, используя функцию pn\_send\_dc\_latch\_frame, которая принимает дескриптор сети, дескриптор устройства, указатель на буфер и размер буфера в качестве аргументов и возвращает количество отправленных байт. Программа также проверяет наличие ошибок при отправке кадра DC Latch, выводит количество отправленных байт на экран, используя функцию printf и форматированные строки. Программа использует мьютекс dc\_latch\_mutex для синхронизации доступа к буферу DC Latch.

Программа проверяет наличие новых кадров DC Latch для каждого устройства, используя функцию pn\_has\_new\_dc\_latch\_frame, которая принимает дескриптор сети и дескриптор устройства в качестве аргументов и возвращает целое число, которое равно 0, если нет новых кадров DC Latch, или больше 0, если есть новые кадры DC Latch. Программа проверяет наличие ошибок при проверке новых кадров DC Latch. Если есть новые кадры DC Latch - программа читает их в буфер dc\_latch\_buffer, используя функцию pn\_read\_dc\_latch\_frame, которая принимает дескриптор сети, дескриптор устройства, указатель на буфер и размер буфера в качестве аргументов и возвращает количество прочитанных байт. Программа также проверяет наличие ошибок при чтении кадра DC Latch, выводит принятый кадр DC Latch на экран, используя функцию printf и форматированные строки. Затем сравнивает принятые данные с отправленными, используя функцию memcmp, которая принимает два указателя на буферы и размер сравниваемых данных в качестве аргументов и возвращает целое число, которое равно 0, если буферы совпадают, или отлично от 0, если буферы различаются. Программа сообщает о результате сравнения на экран, используя функцию printf и форматированные строки. Моя программа использует мьютекс dc\_latch\_mutex для синхронизации доступа к буферу DC Latch.

Закрытие сети profinet. Программа останавливает обмен данными для каждого устройства, используя функцию pn\_stop\_io\_data, которая принимает дескриптор сети и дескриптор устройства в качестве аргументов и возвращает ноль в случае успеха или отрицательное число в случае ошибки. Также проверяет наличие ошибок при остановке обмена данными. Деактивирует дескриптор сети, используя функцию pn\_deactivate, которая принимает дескриптор сети в качестве аргумента и возвращает ноль в случае успеха или отрицательное число в случае ошибки. Также проверяет наличие ошибок при деактивации дескриптора сети. Программа удаляет дескриптор сети и освобождает ресурсы, используя функцию pn\_destroy, которая принимает дескриптор сети в качестве аргумента и возвращает ноль в случае успеха или отрицательное число в случае ошибки. Моя программа также проверяет наличие ошибок при удалении дескриптора сети.

Программа обрабатывает сигнал прерывания (SIGINT). Сигнал прерывания - это специальный сигнал, который посылается программе при нажатии комбинации клавиш Ctrl+C. Сигнал прерывания служит для остановки работы программы по запросу пользователя. Моя программа регистрирует функцию sig\_handler принимающую номер сигнала в качестве аргумента и устанавливающую флаг running в 0, чтобы остановить цикл работы программы. Функция sig\_handler также выводит сообщение о получении сигнала прерывания на экран, используя функцию printf и форматированную строку.












## 4 ТЕХНИКО-ЭКОНОМИЧЕСКОЕ ОБОСНОВАНИЕ
   ## 4.1 Исходные данные для расчёта экономического эффекта
Данный дипломный проект направлен на создание и реализацию модуля, поддерживающего протокол PROFINET, для управляющей программы ptusa\_main с целью повышения функциональности, интеграции и эффективности производственных процессов.

Разработка программного продукта предусматривает проведение практически всех стадий проектирования и относится ко второй группе сложности.  

Последовательность расчетов:

- Расчёт объёма функций программного модуля.
- Расчёт полной себестоимости программного модуля.
- Расчёт отпускной цены и прибыли программного модуля.
  ## 4.2 Расчёт объёма функций программного модуля
Общий объём ПО определяется исходя из объёма функций, реализуемых программой, по формуле (4.1):

V0=i=0nVi,									     (4.1)

где V0 – общий объём ПО;

Vi – объём функций ПО;

n – общее число функций.

Расчет общего объема ПО (количества строк исходного кода предполагает определение объема по каждой функции. В том случае, когда на стадии технико-экономического обоснования проекта невозможно рассчитать точный объем функций, данный объем может быть получен на основании ориентировочной (прогнозной) оценки имеющихся фактических данных по аналогичным проектам, выполненным ранее, или путем применения нормативов по каталогу функций.

На основании информации о функциях разрабатываемого ПО по каталогу функций определяется общий объем ПО. В зависимости от организационных и технологических условий, в которых разрабатывается ПО, корректируется объем на основе экспертных оценок.

Уточнённый объём ПО (Vy) определяется по формуле (4.2):

Vy=i=0nVyi,									     (4.2)

где Vyi – уточнённый объём отдельной функции в строках исходного кода.

Перечень и объём функций ПО приведён в таблице 4.1.

Таблица 4.1 – Перечень и объём функций программного обеспечения

<table><tr><th rowspan="2"><b>№ функции</b></th><th rowspan="2"><p><b>Наименование</b></p><p><b>(содержание)</b></p><p><b>функции</b></p></th><th colspan="2"><b>Объём функции строк исходного кода</b></th></tr>
<tr><td><b>По каталогу (</b>Vy<b>)</b></td><td><b>Уточнённый (</b>Vyi<b>)</b></td></tr>
<tr><td>107</td><td>Организация ввода/вывода информации в интерактивном режиме</td><td>320</td><td>114</td></tr>
<tr><td>405</td><td>Система настройки ПO</td><td>370</td><td>152</td></tr>
<tr><td>501</td><td>Монитор ПО (управление работой компонентов)</td><td>1340</td><td>653</td></tr>
<tr><td>602</td><td>Вспомогательные и сервисные программы</td><td>580</td><td>520</td></tr>
<tr><td colspan="2">Итого:</td><td>2610</td><td><a name="_hlk136883372"></a>1439</td></tr>
</table>

С учётом информации, указанной в таблице 4.1, уточнённый объём ПО составил 1439 строки кода вместо предполагаемого количества 2610.
## 4.3 Расчёт полной себестоимости программного модуля
Стоимостная оценка программного средства у разработчика предполагает составление сметы затрат, которая включает следующие статьи расходов:

- заработную плату исполнителей (основную – ЗПо  и дополнительную – ЗПд);
- отчисления на социальные нужды (Рсоц);
- материалы и комплектующие изделия (Рм);
- спецоборудование (Рс);
- машинное время (Рмв);
- расходы на научные командировки (Рнк);
- прочие прямые расходы (Рпр);
- накладные расходы (Рнр);
- затраты на освоение и сопровождение программного средства (Ро и Рсо).

Полная себестоимость (Сп) разработки программного продукта рассчитывается как сумма расходов по всем статьям с учётом рыночной стоимости аналогичных продуктов. 

Основной статьёй расходов на создание программного продукта является заработная плата разработчиков (исполнителей), в число которых принято включать инженеров-программистов, руководителей проекта, системных архитекторов, дизайнеров, разработчиков баз данных, Web-мастеров и других специалистов, необходимых для решения специальных задач в команде. 

Расчёт заработной платы разработчиков программного продукта начинается с определения:

- продолжительности времени разработки (Фрв), которое устанавливается экспертным путём с учётом сложности, новизны программного модуля и фактически затраченного времени. В данном дипломном проекте Фрв = 2 месяца; 
- количества разработчиков программного обеспечения. В данном дипломном проекте – один разработчик (инженер-программист 11 разряда).

Заработная плата разработчиков определятся как сумма основной и дополнительной заработной платы всех исполнителей. 

Основная заработная плата каждого исполнителя определяется по формуле (4.3):

ЗПосн=Тст.1р\*ТкФэфф.р.в.\*Фрв\*Кпр,						     (4.3)

где Тст.1р – ставка 1 разряда рабочего (на дату написания дипломного проекта – 228 бел.руб.);

Тк – тарифный коэффициент согласно разряду исполнителя;

Фэфф.р.в. – среднее количество рабочих дней – 22 дня;

Фр.в. – фонд рабочего времени исполнителя (продолжительность разработки программного модуля, дни);

Кпр – коэффициент премии, Кпр = 1,5.

Рассчитаем основную заработную плату инженера-программиста согласно формуле 4.3. Тарифный коэффициент согласно 11 разряду инженера-программиста Тк = 1,91. Продолжительность разработки программного продукта – 2 месяца. 

Часовая тарифная ставка определяется по формуле (4.4):

Тчас. ст.1р.=Тмес.ст.1р.\*12Прв.,								     (4.4)

где	Тмес.ст.1р. – месячная тарифная ставка рабочего 1 разряда (на дату написания дипломного проекта – 228 бел.руб.);

Прв. – расчётная норма рабочего времени (в часах) за год, определяется по производственному календарю текущего года (на 2023 г. Для 5-дневной недели при 40-часовой рабочей неделе – 2011 ч.). 

Дополнительная заработная плата каждого исполнителя (Ндоп. зп.  = 20%). Она рассчитывается от основной заработной платы по формуле (4.5):

ЗПдоп=ЗПосн\*Ндоп. зп100%.							     (4.5)

Рассчитаем заработную плату исполнителей проекта и результаты вычислений внесём в таблицу 4.2.

**Таблица 4.2** – Расчет заработной платы

<table><tr><th colspan="1" rowspan="2"><b>Категория работников</b></th><th colspan="1" rowspan="2"><b>Разряд</b></th><th colspan="1" rowspan="2"><b>Тарифные коэффициент (</b>Тк)</th><th colspan="1" rowspan="2">Фэфф.р.в.<b>, (дн.)</b></th><th colspan="1" rowspan="2"><b>Коэффициент премии</b> (Кпр<b>)</b></th><th colspan="1" rowspan="2">Тк <b>(час.)</b></th><th colspan="3"><b>Заработная плата, бел.руб.</b></th></tr>
<tr><td colspan="1"><b>Основная</b></td><td colspan="1"><b>Дополнительная</b></td><td colspan="1"><b>Всего</b></td></tr>
<tr><td colspan="1">Инженер-программист</td><td colspan="1">11</td><td colspan="1">1,91</td><td colspan="1">22</td><td colspan="1">1,3</td><td colspan="1">8</td><td colspan="1">1132,25</td><td colspan="1">226,45</td><td colspan="1">1358,7</td></tr>
</table>

Таким образом, как видно из таблицы, заработная плата инженера- программиста составляет 1358 бел. руб. 70 коп. 

Отчисления на социальные нужды (Рсоц) определяются по формуле (4.6) в соответствии с действующим законодательством по нормативу (29% от дохода – отчисления взносы по пенсионному страхованию для всех категорий работающих граждан; 6% от дохода – взнос на случай временной потери трудоспособности): 

Рсоц=(ЗПосн+ЗПдоп)\*35%100%.						     (4.6)

Расходы по статье «Спецоборудование» (Рс) включает затраты на приобретение технических и программных средств специального назначения, необходимых для разработки методического пособия, включая расходы на проектирование, изготовление, отладку и другое. 

В данном дипломном проекте для разработки программного модуля работы с протоколом PROFINET для управляющей программы ptusa\_main приобретение какого-либо спецоборудования не предусматривалось. Так как спецоборудование не было приобретено, данная статья не рассчитывается. 

По статье «Материалы и комплектующие изделия» (Рм) отражаются расходы на магнитные носители, бумагу, красящие ленты и другие материалы, необходимы для разработки программного продукта. Норма расхода материалов в суммарном выражении определяется в расчете на 100 строк исходного кода по формуле (4.7).

Рм=Нм⋅V0100,									     (4.7)

где	V0 – уточнённый общий объём функций строк исходного кода. Согласно расчётам пункта 4.2 данное значение равно 1439 строк; 

Нм – норма расхода материалов в расчете на 100 строк исходного кода программного продукта. Принимаем равной 0,6 бел. руб. 

По статье «Машинное время» (Рмв) включают оплату машинного времени, необходимого для разработки и отладки программного продукта. Они определяются в машино-часах по нормативам на 100 строк исходного кода машинного времени. Рмв  определяется по формуле (4.8).

Рмв=Цмвi⋅V0100⋅Нмв,								     (4.8)

где	Цмвi – цена одного машинного часа (принимается в размере 0,8 бел. руб.); 

V0 – уточнённый общий объём машинного кода;

Нмв – норматив расхода машинного времени на отладку 100 строк кода, машино-часов. Принимается в размере 0,8. 

Расходы по статье «Научные командировки» (Рнк) берутся либо по смете научных командировок, разрабатываемой на предприятии, либо в процентах от основной заработной платы исполнителей (10-15%). Так как в данном проекте научные командировки не предусмотрены, данная статься не рассчитывается. 

Расходы по статье «Прочие затраты» (Рпр) включают затраты на приобретение специальной научно-технической информации и специальной литературы. Определяются по нормативу в процентах к основной заработной плате исполнителей. Так как специальная научно-техническая информация и специальная литература не приобреталась, то данная статься не рассчитывается. 

Затраты по статье «Накладные расходы» (Рнр) связаны с содержанием вспомогательных хозяйств, а также с расходами на общехозяйственные нужды. Определяется по нормативу в процентах к основной заработной плате по формуле (4.9):

Рнр=Ннр100%⋅ЗПосн,								     (4.9)

где	Ннр – норматив накладных расходов, в данном дипломном проекте норматив накладных расходов равен 80%.

Сумма вышеперечисленных расходов по статься на программный продукт служит исходной базой для расчёта затрат на освоение и сопровождение программного продукта. Они рассчитываются по формуле (4.10).

СЗ=ЗПосн+ЗПдоп+Рсоц+Рм+Рмв+Рнк+Рпр+Рнр.		   (4.10)

Затраты на освоение программного продукта (Ро). Организация-разработчик участвует в освоении программного продукта и несёт соответствующие затраты, на которые составляется смета, оплачиваемая заказчиком по договору. Затраты на освоение определяются по установленному нормативу от суммы затрат по формуле (4.11). 

Ро=СЗ⋅Но100%,									   (4.11)

где	СЗ – сумма вышеперечисленных расходов по статьям на разработку программного продукта; 

Но – установленный норматив затрат на освоение. Для данного дипломного проекта принимается равной 8%.

Затраты на сопровождение программного продукта (Рсо). Организация-разработчик осуществляет сопровождение программного продукта и несёт расходы, которые оплачиваются заказчиком в соответствии с договором и сметой на сопровождение. Эти расходы рассчитываются по формуле (4.12).

Рсо=СЗ\*Нсо100%,								   (4.12)

где	СЗ – сумма вышеперечисленных расходов по статьям на разработку программного продукта; 

Нсо – установленный норматив затрат на сопровождение программного продукта. Для данного дипломного проекта принимается равной 7%. 

Полная себестоимость (СП) разработки программного продукта рассчитывается как сумма расходов по всем статьям. Она определяется по формуле (4.13). 

СП=СЗ+Ро+Рсо,								   (4.13)

Результаты вычислений внесём в таблицу 4.3. 

**Таблица 4.3** – Себестоимость программного продукта

|**Наименование статей затрат**|**Норматив, %**|**Сумма затрат, бел.руб.**|
| :-: | :-: | :-: |
|1. Заработная плата, всего|-|1358,7|
|2. Отчисления на социальные нужды|35|475,55|
|3. Спецоборудование|Не применялось|-|
|4. Материалы|-|8,63|
|5. Машинное время|-|9,21|
|6. Научные командировки|Не планировались|-|
|7. Прочие затраты|-|-|
|8. Накладные расходы|80|905,8|
|9. Сумма затрат|-|2757,89|
|10. Затраты на освоение|8|220,63|
|11. Затраты на сопровождение|7|193,05|
|12. Полная себестоимость|-|3171,57|

В результате всех расчётов полная себестоимость программного продукта составила 3171 бел. руб. 57 коп.

## 4.4 Расчёт цены и прибыли по программному продукту

Для определения цены программного продукта необходимо рассчитать плановую прибыль, которая рассчитывается по формуле (4.14). 

П=СП\*R100%,									   (4.14)

где	СП – полная себестоимость программного модуля, бел. руб.; 

R – уровень рентабельности программного модуля. В данном дипломном проекте уровень рентабельности равен 15%.

После расчета прибыли от реализации по формуле (4.15) определяется прогнозируемая цена программного продукта без налогов.

` `Цп=СП+П,									   (4.15)

где	СП – полная себестоимость программного модуля работы с протоколом PROFINET для управляющей программы ptusa\_main, бел. руб.; 

П – плановая прибыль от реализации программного модуля, бел. руб. 

Отпускная цена (цена реализации) программного продукта включает налог на добавленную стоимость и рассчитывается по формуле (4.16):

Цо=СП+П+НДСпп,							   (4.16)

где	СП – полная себестоимость программного модуля работы с протоколом PROFINET для управляющей программы ptusa\_main, бел. руб.; 

П – плановая прибыль от реализации программного модуля, бел. руб.;

НДСпп – налог на добавленную стоимость. 

Для данного программного продукта НДСпп рассчитывается по формуле (4.17).

НДСпп=Цп\*НДС100%,								   (4.17)

где	Цп – прогнозируемая цена, бел. руб.; 

НДС – налог на добавленную стоимость. В настоящее время он составляет 20%.

Прибыль от реализации программного продукта за вычетом налога на прибыль является чистой прибылью (ПЧ). Чистая прибыль остаётся организации-разработчику и представляет собой экономический эффект от создания нового программного продукта. Она рассчитывается по формуле (4.18):

ПЧ=П\*(1-Нп100%),								   (4.18)

где	П – плановая прибыль от реализации программного модуля, бел. руб.; 

Нп – ставка налога на прибыль. В настоящее время он равен 20%.

Все расчёты цены и прибыли по программному продукту сведены в таблицу 4.4.

**Таблица 4.4** – Расчёт отпускной цены и чистой прибыли программного модуля

|**Наименование статей затрат**|**Норматив, %**|**Сумма затрат, бел. руб.**|
| :-: | :-: | :-: |
|1\. Полная себестоимость|-|3171,57|
|2\. Прибыль|15|475,74|
|3\. Цена без НДС|-|3647,31|
|4\. НДС|20|729,46|
|5\. Отпускная цена|-|4376,77|
|6\. Налог на прибыль|20|71,36|
|7\. Чистая прибыль|-|380,59|

В ходе произведенных расчетов определены основные экономические показатели:

- полная себестоимость – 3171 бел. руб. 57 коп.;
- прогнозируемая цена – 4376 бел. руб. 77 коп.;
- чистая прибыль – 380 бел. руб. 59 коп. 

Разработанный программный продукт имеет малое количество конкурентов с более высокими ценами на их услуги. Таким образом, рассчитанная отпускная цена на программный продукт, разрабатываемой в рамках данного дипломного проекта, является конкурентоспособной. При расчете цены учтены отчисления в фонд социальной защиты, а также налоги, необходимые к уплате. К конечному итогу получаем окончательную цену продукта, равную 4376 бел. руб. 77 коп. 



## 5 ЭНЕРГО- И РЕСУРСОСБЕРЕЖЕНИЕ
   ## 5.1 Основополагающие принципы
Энерго- и ресурсосбережение имеет множество преимуществ для окружающей среды, так как оно способствует снижению выбросов парниковых газов и других загрязняющих веществ в атмосферу, что способствует борьбе с глобальным потеплением и улучшению качества воздуха, снижению потребления воды и сокращению сточных вод, что способствует сохранению водных ресурсов и улучшению качества воды, снижению потребления сырья и повторному использованию отходов, что способствует сокращению объемов отходов и уменьшению нагрузки на свалки и полигоны, снижению потребления энергии и использованию возобновляемых источников энергии, что способствует снижению зависимости от импортных энергоносителей и повышению энергетической безопасности, снижению затрат на экологические платежи, штрафы, компенсации и другие расходы, связанные с нарушением экологического законодательства и нормативов. Таким образом, энерго- и ресурсосбережение способствует не только экономическому, но и экологическому благополучию предприятия и общества в целом.

Кроме того, энерго- и ресурсосбережение имеет множество преимуществ для предприятия, таких как:

- Повышение эффективности и конкурентоспособности предприятия за счет снижения издержек на производство, улучшения качества продукции, увеличения объемов производства и рыночной доли.
- Повышение репутации и имиджа предприятия за счет демонстрации социальной ответственности, участия в экологических программах и проектах, получения сертификатов и наград за достижения в области энерго- и ресурсосбережения.
- Повышение мотивации и лояльности персонала за счет создания комфортных условий труда, стимулирования участия в мероприятиях по энерго- и ресурсосбережению, обучения новым технологиям и методам работы.
- Повышение инновационного потенциала предприятия за счет поиска и внедрения новых технологий, оборудования, материалов, методов и форм организации производства, способствующих снижению потребления ресурсов.

Основополагающими принципами энерго- и ресурсосбережения являются:

- **Принцип комплексности:** при планировании и реализации мероприятий по энерго- и ресурсосбережению необходимо учитывать взаимосвязь всех видов ресурсов (энергии, воды, топлива, сырья, оборудования и т.д.) и их влияние на качество продукции и окружающую среду. Например, снижение потребления электроэнергии может привести к уменьшению выбросов парниковых газов, а повышение эффективности использования воды может сократить затраты на очистку сточных вод. Таким образом, принцип комплексности позволяет достигать синергетического эффекта от мероприятий по энерго- и ресурсосбережению.
- **Принцип системности:** энерго- и ресурсосбережение должно быть организовано как единая система на предприятии, включающая цели, задачи, показатели, мероприятия, ответственность и контроль. Для этого необходимо разработать и реализовать стратегию и тактику энерго- и ресурсосбережения на предприятии, учитывая его специфику, отраслевые особенности, региональные условия, законодательные требования и нормативы. Также необходимо обеспечить координацию и взаимодействие всех подразделений и сотрудников предприятия в процессе энерго- и ресурсосбережения.
- **Принцип экономичности:** все мероприятия по энерго- и ресурсосбережению должны быть экономически обоснованы и эффективны. Для этого необходимо проводить анализ затрат и выгод от мероприятий по энерго- и ресурсосбережению, учитывая как прямые, так и косвенные факторы. Например, при выборе нового оборудования необходимо учитывать не только его стоимость и потребление ресурсов, но и срок службы, стоимость обслуживания и ремонта, влияние на качество продукции и т.д. Также необходимо оценивать риски и возможные последствия от мероприятий по энерго- и ресурсосбережению, такие как снижение надежности работы оборудования, ухудшение условий труда персонала, нарушение технологического процесса и т.д.
- **Принцип инновационности:** для достижения лучших результатов в области энерго- и ресурсосбережения необходимо постоянно поискать и внедрять новые технологии, оборудование, материалы, методы и формы организации производства, способствующие снижению потребления ресурсов. Для этого необходимо следить за передовыми разработками в отрасли.
- **Принцип непрерывности:** постоянный мониторинг, анализ, корректировка и совершенствование мероприятий по энерго- и ресурсосбережению на основе обратной связи.

Энерго- и ресурсосбережение на предприятии – это не только необходимость, но и выгода, так как оно позволяет снизить затраты, повысить эффективность, улучшить качество, укрепить репутацию и способствовать сохранению окружающей среды. Для успешного энерго- и ресурсосбережения на предприятии необходимо придерживаться принципов комплексности, системности, экономичности, инновационности и непрерывности, а также проводить аудит, планирование, реализацию, контроль и оценку мероприятий по энерго- и ресурсосбережению. Энерго- и ресурсосбережение на предприятии – это процесс постоянного совершенствования и развития, требующий участия и поддержки всех заинтересованных сторон.

## 5.2 Преимущества внедрения протокола PROFINET для энерго- и ресурсосбережения

Модуль протокола PROFINET для управляющей программы ptusa\_main успешно реализован и демонстрирует потенциал для повышения энергоэффективности и экономии ресурсов в промышленности. Для того, чтобы разобраться в принципах работы этой технологии, рассмотрим ее основные компоненты и их функции.

PROFINET - это промышленный стандарт коммуникации на основе Ethernet, разработанный компанией Siemens AG в 2002 году в рамках их автоматизационной платформы SIMATIC NET. Он обеспечивает быстрый обмен данными между устройствами на разных сетях с использованием стандартизированных протоколов, таких как TCP/IP или UDP/IP. Это позволяет передавать данные в режиме реального времени между несколькими системами, такими как контроллеры, датчики, приводы, клапаны и т.д., что снижает задержку при управлении машинами или мониторинге процессов на производственных линиях. Например, с помощью PROFINET можно управлять скоростью вращения двигателя в зависимости от температуры или давления в системе, а также получать обратную связь о состоянии оборудования и возможных неисправностях. Также PROFINET поддерживает интеллектуальную интеграцию устройств, что означает, что компоненты системы могут самостоятельно настраиваться без ручного вмешательства со стороны инженеров - что уменьшает время настройки и повышает надежность и производительность. Например, при подключении нового устройства к сети PROFINET оно автоматически определяется и конфигурируется согласно заданным параметрам, а также получает доступ к необходимым данным и сервисам.

С точки зрения энергоэффективности и экономии ресурсов, использование модуля протокола PROFINET в существующих управляющих программах, таких как ptusa\_main, способствует оптимизации времени работы за счет его возможности передавать большие объемы данных быстро на большие расстояния с низким потреблением энергии по сравнению с традиционными методами, такими как последовательные кабели или сети fieldbus. Например, при использовании PROFINET можно передавать данные о расходе топлива или электричества по всему заводу за считанные миллисекунды, что позволяет более точно регулировать потребление энергии и избегать перерасхода. Кроме того, поскольку все подключенные узлы синхронизируются через одну единую сеть, операторы имеют лучший обзор работы машин и могут выявлять области, где ресурсы расходуются неэффективно, и принимать корректирующие меры при необходимости. 

Например, при использовании PROFINET можно отслеживать износ деталей или необходимость замены расходных материалов, что позволяет своевременно проводить техническое обслуживание и предотвращать поломки. Наконец, поскольку он использует открытые стандарты, а не закрытые решения, компаниям не нужно покупать дорогостоящее оборудование, что упрощает им обновление своей инфраструктуры более дешево, когда на рынке появляются новые технологии. Например, при использовании PROFINET можно легко подключать новые устройства или заменять старые без необходимости менять всю сеть или программное обеспечение.

О необходимости и успешности использования протокола PROFINET для обеспечения энергоэффективности, можно судить с появлением профиля PROFIenergy. Этот профиль используется для устройств, которые нельзя полностью выключить на то время, когда они не используются. Устройства, поддерживающие PROFIenergy, после получения команды от системы (центрального контроллера или контроллера-супервайзера) переходят через определенный промежуток времени в спящий режим. Также система включает устройство за заданный промежуток времени до начала использования, чтобы оно «прогрелось» и прошли переходные процессы.

Поддержка PROFIenergy осуществляется на уровне прошивки IO контроллера. Кроме этого, подключаемое к контроллеру оборудование должно иметь возможность управления энергосбережением через команды PROFIenergy. Поддержка PROFIenergy в продукции Siemens реализована в модулях серий ET200S, ET200SP, ET200MP, ET200Pro (в зависимости от версии прошивки). Примерами могут служить блок питания PM-E (номер продукта 6ES7138-4CB11-0AB0) и модуль пуска мотора (номер продукта 3RK1903-1BC00) в серии ET200S.

По каждому устройству в прошивке прописывается минимально допустимое время паузы и время включения (Time to Operate), т. е. время, требуемое на прогрев устройства. Эти данные, наряду с текущим состоянием и перечнем доступных функций энергосбережения, запрашиваются системой у IO-контроллера.

За время, равное значению Time to Operate, система передает на контроллер сигнал о завершении паузы. После окончания времени, отведенного на запуск, IO-контроллер отвечает, что устройство готово к выполнению задания. И только после этого на устройство будут подаваться управляющие сигналы о выполнении каких-либо действий. Такая многоступенчатая система обеспечивает высокий уровень безопасности и защиту от поломки оборудования.

![](Aspose.Words.14d01eac-c179-4c5f-91ee-ea1907226535.017.jpeg)

Рисунок 5.1 – Запуск оборудования после паузы.

В общем, использование модуля протокола PROFENIT в существующих управляющих программах, таких как ptusa\_main, дает много преимуществ для оптимизации оперативной эффективности и сохранения энергии и ресурсов в промышленности. Он позволяет передавать данные между несколькими системами быстро и без потери качества и производительности. Это дает производителям гибкость для адаптации к меняющимся требованиям отрасли сегодня и эффективного и ответственного использования ресурсов завтра.



**ЗАКЛЮЧЕНИЕ**


В ходе дипломного проектирования был разработан модуль для работы с протоколом PROFINET для управляющей программы ptusa\_main. Модуль содержит следующие методы:

1\. метод инициализации сети PROFINET

2\. метод для обмена данными с устройствами по протоколу PROFINET

3\. метод для генерации и отправки DC Latch фрейма

4\. метод для получения и обработки DC Latch фрейма

5\. метод для завершения сети PROFINET.

В ходе дипломного проектирования были выполнены следующие задачи:

- был проведен анализ предметной области, где были рассмотрены методы и способы автоматизации производства, основные теоретические сведения и понятия, необходимые для понимания предмета автоматизации и некоторых деталей, необходимых для дальнейшей разработки модуля;
- был проведен анализ и описание сетевых протоколов в контексте автоматизации производства, где была представлена классификация протоколов по различным критериям, а также описаны уровни модели OSI и часто используемые протоколы в рамках автоматизации масштабных производственных процессов;
- было проведено обоснование разработки, постановка задачи и определение целей и требований к модулю;
- был проведен анализ существующих решений по теме, где были рассмотрены различные программно-аппаратные платформы, их функции, особенности, преимущества и сферы применения, а также обоснован выбор программно-аппаратной платформы для реализации модуля;
- была описана аппаратная часть системы, включающая контроллер, на котором запускается управляющая программа, его характеристики и детали работы с ним;
- был проведен детальный разбор принципа работы протокола PROFINET, его преимущества и процесс прохождения данных по устройствам, а также описаны способы синхронизации и управления временем устройств в сети и программные средства реализации модуля;
- была выполнена реализация и испытание системы, где была описана управляющая платформа, функции модуля, его возможности расширения и улучшения в дальнейшем;
- было проведено технико-экономическое обоснование, где была доказана экономическая выгоду от реализации дипломного проекта.

